version: "3.2"
services:
  api:
    image: taxi_api
    build:
      context: ./api
      target: build
    ports:
      - "80:5000"
    environment:
      - FLASK_APP=app
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    depends_on:
      - redis
      - model_duration
      - model_fare

  redis:
    image: redis:6.2.6

  model_duration:
    image: ml_service_duration
    build:
      context: /
      dockerfile: ./model_duration/Dockerfile
      target: build
    depends_on:
      - redis

  model_fare:
    image: ml_service_fare
    build:
      context: /
      dockerfile: ./model_fare/Dockerfile
      target: build
    depends_on:
      - redis